name: Zip Modified Files

on:
  workflow_dispatch:

jobs:
  zip-modified:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository to access the files
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Identify new or modified files and create a zip archive
    - name: Create zip of new/modified files
      id: zip_files
      run: |
        # Find new or modified files (excluding deleted ones)
        git diff --name-only --diff-filter=ACM > modified_files.txt
        
        # Check if there are any changes
        if [ -s modified_files.txt ]; then
          # Create zip while keeping folder structure
          zip -r modified_files.zip -@ < modified_files.txt
          echo "zip_created=true" >> $GITHUB_ENV
        else
          echo "No new or modified files to zip."
          echo "zip_created=false" >> $GITHUB_ENV
        fi

    # 3. Upload the zip file as an artifact for download, if it was created
    - name: Upload zip as artifact
      if: env.zip_created == 'true'
      uses: actions/upload-artifact@v3
      with:
        name: modified-files-zip
        path: modified_files.zip
